name: Publish pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm i
          npm run generate
        env:
          CI: true

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
        # Include all JS files from the `dist` directory
          file-path: |
              dist/*
          commit-msg: Github action push dist/
          github-token: ${{ secrets.GITHUB_TOKEN }}
